version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "1547:3001"
    depends_on:
      - db
    volumes:
      - ./backend:/app  

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crm
    ports:
      - "1546:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
